sonar.organization=nnigarp
sonar.projectKey=Nnigarp_AS_202620_PROYECTO_CAMPUSMARKET

sonar.sources=backend/app
sonar.tests=backend/tests
sonar.python.version=3.12

sonar.exclusions=**/__pycache__/**,**/.pytest_cache/**,frontend/campusmarket/build/**
